name: Auto NIC packager

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  packager:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Theos
        uses: pypush/actions-setup-theos@v1

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS-Mod-Menu
          path: ./*.dylib
